import type { TldPriceInfo } from "@/lib/types/domain";

export const POPULAR_TLDS = [
  "com",
  "dev",
  "net",
  "org",
  "io",
  "ai",
  "xyz",
  "app",
  "co",
  "me",
  "pro",
  "tech",
] as const;

export const TLD_DIRECTORY: TldPriceInfo[] = [
  {
    tld: "com",
    category: "popular",
    registrationPrice: 11.25,
    renewalPrice: 11.25,
    transferPrice: 11.25,
    description: "The undisputed global standard for businesses and personal brands.",
    isPopular: true,
  },
  {
    tld: "dev",
    category: "tech",
    registrationPrice: 8.75,
    renewalPrice: 12.87,
    transferPrice: 12.87,
    description: "A secure, modern domain dedicated to developers and technology builders.",
    isPopular: true,
    isPromo: true,
  },
  {
    tld: "io",
    category: "tech",
    registrationPrice: 28.12,
    renewalPrice: 51.80,
    transferPrice: 51.80,
    description: "The iconic domain extension for startups, open-source projects, and SaaS.",
    isPopular: true,
  },
  {
    tld: "ai",
    category: "tech",
    registrationPrice: 82.70,
    renewalPrice: 82.70,
    transferPrice: 165.09,
    description: "The gold standard for artificial intelligence companies and machine learning tools.",
    isPopular: true,
  },
  {
    tld: "xyz",
    category: "popular",
    registrationPrice: 2.04,
    renewalPrice: 14.21,
    transferPrice: 14.21,
    description: "Next-generation versatile domain for innovators, creatives, and Web3.",
    isPopular: true,
    isPromo: true,
  },
  {
    tld: "net",
    category: "popular",
    registrationPrice: 12.52,
    renewalPrice: 12.52,
    transferPrice: 12.52,
    description: "One of the original top-level domains, trusted for digital infrastructure.",
    isPopular: true,
  },
  {
    tld: "org",
    category: "popular",
    registrationPrice: 11.33,
    renewalPrice: 14.98,
    transferPrice: 14.98,
    description: "Universally trusted for organizations, communities, and public initiatives.",
    isPopular: true,
  },
  {
    tld: "app",
    category: "tech",
    registrationPrice: 14.00,
    renewalPrice: 17.50,
    transferPrice: 17.50,
    description: "Built-in HTTPS security for mobile, web, and desktop applications.",
    isPopular: true,
  },
  {
    tld: "co",
    category: "business",
    registrationPrice: 10.98,
    renewalPrice: 26.50,
    transferPrice: 26.50,
    description: "Short, modern, and memorable for emerging companies and entrepreneurs.",
    isPopular: true,
  },
  {
    tld: "tech",
    category: "tech",
    registrationPrice: 4.99,
    renewalPrice: 48.00,
    transferPrice: 48.00,
    description: "Direct branding for technology firms, hardware, and engineering teams.",
    isPromo: true,
  },
  {
    tld: "design",
    category: "creative",
    registrationPrice: 7.99,
    renewalPrice: 52.00,
    transferPrice: 52.00,
    description: "Dedicated to UI/UX designers, studios, graphic artists, and creators.",
  },
  {
    tld: "me",
    category: "popular",
    registrationPrice: 8.50,
    renewalPrice: 19.99,
    transferPrice: 19.99,
    description: "The perfect extension for personal portfolios, resumes, and personal brands.",
    isPopular: true,
  },
  {
    tld: "pro",
    category: "business",
    registrationPrice: 3.99,
    renewalPrice: 18.50,
    transferPrice: 18.50,
    description: "Communicate credibility, expertise, and verified professional services.",
    isPromo: true,
  },
  {
    tld: "site",
    category: "niche",
    registrationPrice: 1.99,
    renewalPrice: 28.00,
    transferPrice: 28.00,
    description: "Affordable and universally recognized for any website concept.",
    isPromo: true,
  },
  {
    tld: "online",
    category: "niche",
    registrationPrice: 2.49,
    renewalPrice: 34.00,
    transferPrice: 34.00,
    description: "Clear signal that your business or platform is open for digital business.",
    isPromo: true,
  },
];
